swagger: "2.0"
info:
  description: "Contact web services"
  version: "0.0.1"
  title: "Contact Services"
  contact:
    email: "MDCP-MDM_Contact-Interest@groups.int.hpe.com"
host: "localhost:8080"
basePath: "/"
tags:
- name: "Contacts"
  description: "Contact Web Services Operations"
schemes:
- "http"
paths:
  /contact/create:
    post:
      tags:
        - "Contacts"
      summary: "Creates a new user"
      description: "Creates a new contact"
      operationId: "create"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Contact Parameters"
        required: true
        schema:
          $ref: "#/Request"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/Response"
  /contact/lookup:
    post:
      tags:
        - "Contacts"
      summary: "Lookup for contact"
      description: "Lookup for contact with compose id"
      operationId: "lookup"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Contact Parameters"
        required: true
        schema:
          $ref: "#/LookupRequest"
      - in: "query"
        name: "privacy"
        description: "Return only privacy content"
        required: false
        type: "string"
        enum:
          - "N"
          - "Y"
        default: "N"
      responses:
        200:
          description: "successful operation"
          schema:
            ObjectResponse:
              type: 'object'
              oneOf:
                - $ref: "#/LookupResponse"
                - $ref: "#/LookupResponsePrivacyOnly"
  /contact/lookup/{mdmContactID}:
    get:
      tags:
        - "Contacts"
      summary: "Find contact by id"
      description: "Returns a contact"
      operationId: "lookupById"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "mdmContactID"
        description: "Id of contact to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "query"
        name: "privacy"
        description: "Return only privacy content"
        required: false
        type: "string"
        enum:
          - "N"
          - "Y"
        default: "N"
      responses:
        200:
          description: "successful operation"
          schema:
            ObjectResponse:
              type: 'object'
              oneOf:
                - $ref: "#/LookupResponse"
                - $ref: "#/LookupResponsePrivacyOnly"
        400:
          description: "invalid Id supplied"
        404:
          description: "pet not found"
  /contact/relationship/create:
    post:
      tags:
        - "Contacts"
      summary: "Creates a contactrelationship"
      description: "Creates a contactrelationship"
      operationId: "createContactRelationship"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "contactrelationship Parameters"
        required: true
        schema:
           $ref: "#/ContactRelationshipCreate"
      responses:
        200:
          description: "successful operation"
          schema:
             $ref: "#/ContactRelationshipCreate"
        201:
          description: "Contact Relationship Created Successfully"  
        400:
          description: "Invalid Data"
          
          
          
          
  /contact/privacy/update/locator/email:
    put:
      tags:
        - "Contacts"
      summary: "Updates the privacy by email"
      description: "Updates the privacy by email"
      operationId: "contactPrivacyUpdateByEmail"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Update the contact privacy by email"
        required: true
        schema:
          $ref: "#/ContactPrivacyUpdateByEmail"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/ContactPrivacyUpdateByEmail"
        400:
          description: "Invalid Data"
              
  /contact/privacy/update/locator/telephone:
    put:
      tags:
        - "Contacts"
      summary: "Updates the privacy by telephone"
      description: "Updates the privacy by telephone"
      operationId: "contactPrivacyUpdateByTelephone"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Update the contact privacy by telephone"
        required: true
        schema:
            $ref: "#/ContactPrivacyUpdateByTelephone"
      responses:
        200:
          description: "successful operation"
          schema:
             $ref: "#/ContactPrivacyUpdateByTelephone"
        400:
          description: "Invalid Data"
        
   

definitions:
  Request:
    $ref: './definitions/index.yml#/Request'
  Response:
    $ref: './definitions/index.yml#/Response'
  LookupRequest:
    $ref: './definitions/lookupRequest.yml#/LookupRequest'
  LookupResponse:
    $ref: './definitions/lookupResponse.yml#/LookupResponse'
  LookupResponsePrivacyOnly:
    $ref: './definitions/lookupResponse.yml#/LookupResponsePrivacyOnly'
  ContactRelationshipCreate:
     $ref: './definitions/contactRelationshipCreate.yml#/ContactRelationshipCreate'
  ContactPrivacyUpdateByEmail:
     $ref: './definitions/contactPrivacyUpdateByEmail.yml#/ContactPrivacyUpdateByEmail'
  ContactPrivacyUpdateByTelephone:
     $ref: './definitions/contactPrivacyUpdateByTelephone.yml#/ContactPrivacyUpdateByTelephone'  
  
